// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRBTjAgKpuTntvWtKLsPvFUDQ4Jj7r7A',
    appId: '1:520589032132:web:6735d474c70d88f3116791',
    messagingSenderId: '520589032132',
    projectId: 'tasker-ap',
    authDomain: 'tasker-ap.firebaseapp.com',
    storageBucket: 'tasker-ap.firebasestorage.app',
    measurementId: 'G-LQP1RQE7XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIDsYKMlX33MturzPw5_U4GnHXTxz9NlE',
    appId: '1:520589032132:android:77d0d63c253901ae116791',
    messagingSenderId: '520589032132',
    projectId: 'tasker-ap',
    storageBucket: 'tasker-ap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-DPgBfpokgMPzBIYddlb2EcnSwhxdgqg',
    appId: '1:520589032132:ios:7f2a90aef8e91169116791',
    messagingSenderId: '520589032132',
    projectId: 'tasker-ap',
    storageBucket: 'tasker-ap.firebasestorage.app',
    androidClientId:
        '520589032132-q2j3i695o6gvifhqr6ul34ik5fg5om14.apps.googleusercontent.com',
    iosClientId:
        '520589032132-pd62q93aduilc5ht1spqtm8i8ao3icv8.apps.googleusercontent.com',
    iosBundleId: 'app.tasker.tasker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-DPgBfpokgMPzBIYddlb2EcnSwhxdgqg',
    appId: '1:520589032132:ios:7f2a90aef8e91169116791',
    messagingSenderId: '520589032132',
    projectId: 'tasker-ap',
    storageBucket: 'tasker-ap.firebasestorage.app',
    androidClientId:
        '520589032132-q2j3i695o6gvifhqr6ul34ik5fg5om14.apps.googleusercontent.com',
    iosClientId:
        '520589032132-pd62q93aduilc5ht1spqtm8i8ao3icv8.apps.googleusercontent.com',
    iosBundleId: 'app.tasker.tasker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMRBTjAgKpuTntvWtKLsPvFUDQ4Jj7r7A',
    appId: '1:520589032132:web:db6c6b56e87f9339116791',
    messagingSenderId: '520589032132',
    projectId: 'tasker-ap',
    authDomain: 'tasker-ap.firebaseapp.com',
    storageBucket: 'tasker-ap.firebasestorage.app',
    measurementId: 'G-ZKWWF5CLYG',
  );
}
